In [1]:
import numpy as np

In [3]:
revenue=np.array([[180,200,220],[24,36,40],[12,18,20]])
expenses=np.array([[80,90,100],[10,16,20],[8,10,10]])

In [4]:
profit=revenue-expenses
profit 

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [6]:
price_per_units=np.array([[1000,400,1200]])
units=np.array([[30,40,50],[5,10,15],[2,5,7]])

In [7]:
price_per_units*units

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

In [8]:
#This just multiplied 1000 with 30,400 with 40,1200 with 50 and again
#1000 with 5,400 with 10,1200 with 15 and so on ... This concept is called
#numpy broadcast ie,if shape of 2 matrix is not same it it will try to expand it
#like price_per_units=np.array([[1000,400,1200],[1000,400,1200],[1000,400,1200]])

In [9]:
#numpy broadcast can be proved by the below code

In [10]:
price_per_units=np.array([[1000,400,1200],[1000,400,1200],[1000,400,1200]])
units=np.array([[30,40,50],[5,10,15],[2,5,7]])
price_per_units*units

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

In [12]:
#we need to find dot product
price_per_units=np.array([[1000,400,1200]])
units=np.array([[30,40,50],[5,10,15],[2,5,7]])
np.dot(price_per_units,units)

array([[34400, 50000, 64400]])

In [ ]:
#This shows the sales amount in year 2018,2019 and 2020